### ISSUE TITLE
Relationship between database and image folder

### ISSUE THREAD

**Issue by rkargon** [rkargon/argus#3]
How do we keep track of which folder a database corresponds to?
Right now we store the folder path in the db, but that could be broken if people share a folder.

**Comment by tuckerchapin** [comment]
How would it get broken? Can't you just store a relative path? Like path/to/Dropbox/sorted-folder right?

**Comment by rkargon** [comment]
1. Right now we store an absolute path to the folder, eg
/Users/raphaelkargon/Dropbox/image-folder. We could change that to
relative, something like ~/Dropbox/image-folder

2. but what if another user has his dropbox in
~/weird-subdir/Dropbox/image-folder  or something like that?
Or if it's not in dropbox but synced some other way? There's no guarantee
that the paths will match up on different computers
​

**Comment by rkargon** [comment]
We could just tell people that if they want to sync, they need to have the same relative path form the db file to the folder, like db_path/../image-folder or whatever. It can be in different absolute locations, but the relative path will be the same and it won't complain.
